Update absl-py to version 0.15.0
AnacondaRecipes/absl-py-feedstock pull request #6
Opened 2021-12-01 15:28 UTC by varlackc

absl-py version 0.15.0

1. check the upstream
    https://github.com/abseil/abseil-py/releases/tag/pypi-v0.15.0

2. check the pinnings
3. check the changelogs

4. additional research
    http://github.com/conda-forge/absl-py-feedstock/issues

    No issues at the time of the review

5. verify dev_url
    https://github.com/abseil/abseil-py

6. verify doc_url
    https://abseil.io/docs/

7. pip in the test section
8. veriy the test section
9. additional tests

In order to test the `absl-py` package version `0.15.0` the folowing
command was used:
`conda build absl-py-feedstock --test`
the test result was the following:
`All tests passed`

Based on the research findings and the test results we can conclude
that it is safe to update `absl-py` to version `0.15.0`

2021-12-03 10:44 UTC, skupr-anaconda requested changes

2021-12-03 10:44 UTC, skupr-anaconda commented on recipe/meta.yaml
> +{% set version = "0.15.0" %}
The latest version is 1.0.0

2021-12-03 10:44 UTC, skupr-anaconda commented on recipe/meta.yaml
In host use `setuptools >=24.2`, see https://github.com/abseil/abseil-py/blob/0f86230d77cd90ea1236f0cbee4df9a9b290ef66/setup.py#L42

2021-12-03 10:44 UTC, skupr-anaconda commented on recipe/meta.yaml
In run use `python >=3.6`

2021-12-03 10:44 UTC, skupr-anaconda commented on recipe/meta.yaml
In the test/requires should be `python <3.10`

2021-12-03 10:44 UTC, skupr-anaconda commented on recipe/meta.yaml
The license name should be: `Apache-2.0`

2021-12-08 12:00 UTC, skupr-anaconda commented
@varlackc Should we merge or close this PR?

2021-12-18 04:49 UTC, merged

2021-12-18 04:54 UTC, varlackc commented
> @varlackc Should we merge or close this PR?

The PR has been merged